###############################################################################
#
# This is the make file of proejct of COMP90045, Programming Language
# Implementation.
#
###############################################################################

Goat: Goat.hs GoatParser.hs GoatAST.hs GoatPrettyPrint.hs
	ghc Goat.hs -o Goat

clean:
	rm -f *.o *.hi *.out
	rm -f Goat
